using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using DodoPayments.Client.Exceptions;

namespace DodoPayments.Client.Models.Payments;

[JsonConverter(typeof(PaymentMethodTypesConverter))]
public enum PaymentMethodTypes
{
    Ach,
    Affirm,
    AfterpayClearpay,
    Alfamart,
    AliPay,
    AliPayHk,
    Alma,
    AmazonPay,
    ApplePay,
    Atome,
    Bacs,
    BancontactCard,
    Becs,
    Benefit,
    Bizum,
    Blik,
    Boleto,
    BcaBankTransfer,
    BniVa,
    BriVa,
    CardRedirect,
    CimbVa,
    Classic,
    Credit,
    CryptoCurrency,
    Cashapp,
    Dana,
    DanamonVa,
    Debit,
    DuitNow,
    Efecty,
    Eft,
    Eps,
    Fps,
    Evoucher,
    Giropay,
    Givex,
    GooglePay,
    GoPay,
    Gcash,
    Ideal,
    Interac,
    Indomaret,
    Klarna,
    KakaoPay,
    LocalBankRedirect,
    MandiriVa,
    Knet,
    MBWay,
    MobilePay,
    Momo,
    MomoAtm,
    Multibanco,
    OnlineBankingThailand,
    OnlineBankingCzechRepublic,
    OnlineBankingFinland,
    OnlineBankingFpx,
    OnlineBankingPoland,
    OnlineBankingSlovakia,
    Oxxo,
    PagoEfectivo,
    PermataBankTransfer,
    OpenBankingUk,
    PayBright,
    Paypal,
    Paze,
    Pix,
    PaySafeCard,
    Przelewy24,
    PromptPay,
    Pse,
    RedCompra,
    RedPagos,
    SamsungPay,
    Sepa,
    SepaBankTransfer,
    Sofort,
    Swish,
    TouchNGo,
    Trustly,
    Twint,
    UpiCollect,
    UpiIntent,
    Vipps,
    VietQr,
    Venmo,
    Walley,
    WeChatPay,
    SevenEleven,
    Lawson,
    MiniStop,
    FamilyMart,
    Seicomart,
    PayEasy,
    LocalBankTransfer,
    Mifinity,
    OpenBankingPis,
    DirectCarrierBilling,
    InstantBankTransfer,
    Billie,
    Zip,
    RevolutPay,
    NaverPay,
    Payco,
}

sealed class PaymentMethodTypesConverter : JsonConverter<PaymentMethodTypes>
{
    public override PaymentMethodTypes Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "ach" => PaymentMethodTypes.Ach,
            "affirm" => PaymentMethodTypes.Affirm,
            "afterpay_clearpay" => PaymentMethodTypes.AfterpayClearpay,
            "alfamart" => PaymentMethodTypes.Alfamart,
            "ali_pay" => PaymentMethodTypes.AliPay,
            "ali_pay_hk" => PaymentMethodTypes.AliPayHk,
            "alma" => PaymentMethodTypes.Alma,
            "amazon_pay" => PaymentMethodTypes.AmazonPay,
            "apple_pay" => PaymentMethodTypes.ApplePay,
            "atome" => PaymentMethodTypes.Atome,
            "bacs" => PaymentMethodTypes.Bacs,
            "bancontact_card" => PaymentMethodTypes.BancontactCard,
            "becs" => PaymentMethodTypes.Becs,
            "benefit" => PaymentMethodTypes.Benefit,
            "bizum" => PaymentMethodTypes.Bizum,
            "blik" => PaymentMethodTypes.Blik,
            "boleto" => PaymentMethodTypes.Boleto,
            "bca_bank_transfer" => PaymentMethodTypes.BcaBankTransfer,
            "bni_va" => PaymentMethodTypes.BniVa,
            "bri_va" => PaymentMethodTypes.BriVa,
            "card_redirect" => PaymentMethodTypes.CardRedirect,
            "cimb_va" => PaymentMethodTypes.CimbVa,
            "classic" => PaymentMethodTypes.Classic,
            "credit" => PaymentMethodTypes.Credit,
            "crypto_currency" => PaymentMethodTypes.CryptoCurrency,
            "cashapp" => PaymentMethodTypes.Cashapp,
            "dana" => PaymentMethodTypes.Dana,
            "danamon_va" => PaymentMethodTypes.DanamonVa,
            "debit" => PaymentMethodTypes.Debit,
            "duit_now" => PaymentMethodTypes.DuitNow,
            "efecty" => PaymentMethodTypes.Efecty,
            "eft" => PaymentMethodTypes.Eft,
            "eps" => PaymentMethodTypes.Eps,
            "fps" => PaymentMethodTypes.Fps,
            "evoucher" => PaymentMethodTypes.Evoucher,
            "giropay" => PaymentMethodTypes.Giropay,
            "givex" => PaymentMethodTypes.Givex,
            "google_pay" => PaymentMethodTypes.GooglePay,
            "go_pay" => PaymentMethodTypes.GoPay,
            "gcash" => PaymentMethodTypes.Gcash,
            "ideal" => PaymentMethodTypes.Ideal,
            "interac" => PaymentMethodTypes.Interac,
            "indomaret" => PaymentMethodTypes.Indomaret,
            "klarna" => PaymentMethodTypes.Klarna,
            "kakao_pay" => PaymentMethodTypes.KakaoPay,
            "local_bank_redirect" => PaymentMethodTypes.LocalBankRedirect,
            "mandiri_va" => PaymentMethodTypes.MandiriVa,
            "knet" => PaymentMethodTypes.Knet,
            "mb_way" => PaymentMethodTypes.MBWay,
            "mobile_pay" => PaymentMethodTypes.MobilePay,
            "momo" => PaymentMethodTypes.Momo,
            "momo_atm" => PaymentMethodTypes.MomoAtm,
            "multibanco" => PaymentMethodTypes.Multibanco,
            "online_banking_thailand" => PaymentMethodTypes.OnlineBankingThailand,
            "online_banking_czech_republic" => PaymentMethodTypes.OnlineBankingCzechRepublic,
            "online_banking_finland" => PaymentMethodTypes.OnlineBankingFinland,
            "online_banking_fpx" => PaymentMethodTypes.OnlineBankingFpx,
            "online_banking_poland" => PaymentMethodTypes.OnlineBankingPoland,
            "online_banking_slovakia" => PaymentMethodTypes.OnlineBankingSlovakia,
            "oxxo" => PaymentMethodTypes.Oxxo,
            "pago_efectivo" => PaymentMethodTypes.PagoEfectivo,
            "permata_bank_transfer" => PaymentMethodTypes.PermataBankTransfer,
            "open_banking_uk" => PaymentMethodTypes.OpenBankingUk,
            "pay_bright" => PaymentMethodTypes.PayBright,
            "paypal" => PaymentMethodTypes.Paypal,
            "paze" => PaymentMethodTypes.Paze,
            "pix" => PaymentMethodTypes.Pix,
            "pay_safe_card" => PaymentMethodTypes.PaySafeCard,
            "przelewy24" => PaymentMethodTypes.Przelewy24,
            "prompt_pay" => PaymentMethodTypes.PromptPay,
            "pse" => PaymentMethodTypes.Pse,
            "red_compra" => PaymentMethodTypes.RedCompra,
            "red_pagos" => PaymentMethodTypes.RedPagos,
            "samsung_pay" => PaymentMethodTypes.SamsungPay,
            "sepa" => PaymentMethodTypes.Sepa,
            "sepa_bank_transfer" => PaymentMethodTypes.SepaBankTransfer,
            "sofort" => PaymentMethodTypes.Sofort,
            "swish" => PaymentMethodTypes.Swish,
            "touch_n_go" => PaymentMethodTypes.TouchNGo,
            "trustly" => PaymentMethodTypes.Trustly,
            "twint" => PaymentMethodTypes.Twint,
            "upi_collect" => PaymentMethodTypes.UpiCollect,
            "upi_intent" => PaymentMethodTypes.UpiIntent,
            "vipps" => PaymentMethodTypes.Vipps,
            "viet_qr" => PaymentMethodTypes.VietQr,
            "venmo" => PaymentMethodTypes.Venmo,
            "walley" => PaymentMethodTypes.Walley,
            "we_chat_pay" => PaymentMethodTypes.WeChatPay,
            "seven_eleven" => PaymentMethodTypes.SevenEleven,
            "lawson" => PaymentMethodTypes.Lawson,
            "mini_stop" => PaymentMethodTypes.MiniStop,
            "family_mart" => PaymentMethodTypes.FamilyMart,
            "seicomart" => PaymentMethodTypes.Seicomart,
            "pay_easy" => PaymentMethodTypes.PayEasy,
            "local_bank_transfer" => PaymentMethodTypes.LocalBankTransfer,
            "mifinity" => PaymentMethodTypes.Mifinity,
            "open_banking_pis" => PaymentMethodTypes.OpenBankingPis,
            "direct_carrier_billing" => PaymentMethodTypes.DirectCarrierBilling,
            "instant_bank_transfer" => PaymentMethodTypes.InstantBankTransfer,
            "billie" => PaymentMethodTypes.Billie,
            "zip" => PaymentMethodTypes.Zip,
            "revolut_pay" => PaymentMethodTypes.RevolutPay,
            "naver_pay" => PaymentMethodTypes.NaverPay,
            "payco" => PaymentMethodTypes.Payco,
            _ => (PaymentMethodTypes)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        PaymentMethodTypes value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                PaymentMethodTypes.Ach => "ach",
                PaymentMethodTypes.Affirm => "affirm",
                PaymentMethodTypes.AfterpayClearpay => "afterpay_clearpay",
                PaymentMethodTypes.Alfamart => "alfamart",
                PaymentMethodTypes.AliPay => "ali_pay",
                PaymentMethodTypes.AliPayHk => "ali_pay_hk",
                PaymentMethodTypes.Alma => "alma",
                PaymentMethodTypes.AmazonPay => "amazon_pay",
                PaymentMethodTypes.ApplePay => "apple_pay",
                PaymentMethodTypes.Atome => "atome",
                PaymentMethodTypes.Bacs => "bacs",
                PaymentMethodTypes.BancontactCard => "bancontact_card",
                PaymentMethodTypes.Becs => "becs",
                PaymentMethodTypes.Benefit => "benefit",
                PaymentMethodTypes.Bizum => "bizum",
                PaymentMethodTypes.Blik => "blik",
                PaymentMethodTypes.Boleto => "boleto",
                PaymentMethodTypes.BcaBankTransfer => "bca_bank_transfer",
                PaymentMethodTypes.BniVa => "bni_va",
                PaymentMethodTypes.BriVa => "bri_va",
                PaymentMethodTypes.CardRedirect => "card_redirect",
                PaymentMethodTypes.CimbVa => "cimb_va",
                PaymentMethodTypes.Classic => "classic",
                PaymentMethodTypes.Credit => "credit",
                PaymentMethodTypes.CryptoCurrency => "crypto_currency",
                PaymentMethodTypes.Cashapp => "cashapp",
                PaymentMethodTypes.Dana => "dana",
                PaymentMethodTypes.DanamonVa => "danamon_va",
                PaymentMethodTypes.Debit => "debit",
                PaymentMethodTypes.DuitNow => "duit_now",
                PaymentMethodTypes.Efecty => "efecty",
                PaymentMethodTypes.Eft => "eft",
                PaymentMethodTypes.Eps => "eps",
                PaymentMethodTypes.Fps => "fps",
                PaymentMethodTypes.Evoucher => "evoucher",
                PaymentMethodTypes.Giropay => "giropay",
                PaymentMethodTypes.Givex => "givex",
                PaymentMethodTypes.GooglePay => "google_pay",
                PaymentMethodTypes.GoPay => "go_pay",
                PaymentMethodTypes.Gcash => "gcash",
                PaymentMethodTypes.Ideal => "ideal",
                PaymentMethodTypes.Interac => "interac",
                PaymentMethodTypes.Indomaret => "indomaret",
                PaymentMethodTypes.Klarna => "klarna",
                PaymentMethodTypes.KakaoPay => "kakao_pay",
                PaymentMethodTypes.LocalBankRedirect => "local_bank_redirect",
                PaymentMethodTypes.MandiriVa => "mandiri_va",
                PaymentMethodTypes.Knet => "knet",
                PaymentMethodTypes.MBWay => "mb_way",
                PaymentMethodTypes.MobilePay => "mobile_pay",
                PaymentMethodTypes.Momo => "momo",
                PaymentMethodTypes.MomoAtm => "momo_atm",
                PaymentMethodTypes.Multibanco => "multibanco",
                PaymentMethodTypes.OnlineBankingThailand => "online_banking_thailand",
                PaymentMethodTypes.OnlineBankingCzechRepublic => "online_banking_czech_republic",
                PaymentMethodTypes.OnlineBankingFinland => "online_banking_finland",
                PaymentMethodTypes.OnlineBankingFpx => "online_banking_fpx",
                PaymentMethodTypes.OnlineBankingPoland => "online_banking_poland",
                PaymentMethodTypes.OnlineBankingSlovakia => "online_banking_slovakia",
                PaymentMethodTypes.Oxxo => "oxxo",
                PaymentMethodTypes.PagoEfectivo => "pago_efectivo",
                PaymentMethodTypes.PermataBankTransfer => "permata_bank_transfer",
                PaymentMethodTypes.OpenBankingUk => "open_banking_uk",
                PaymentMethodTypes.PayBright => "pay_bright",
                PaymentMethodTypes.Paypal => "paypal",
                PaymentMethodTypes.Paze => "paze",
                PaymentMethodTypes.Pix => "pix",
                PaymentMethodTypes.PaySafeCard => "pay_safe_card",
                PaymentMethodTypes.Przelewy24 => "przelewy24",
                PaymentMethodTypes.PromptPay => "prompt_pay",
                PaymentMethodTypes.Pse => "pse",
                PaymentMethodTypes.RedCompra => "red_compra",
                PaymentMethodTypes.RedPagos => "red_pagos",
                PaymentMethodTypes.SamsungPay => "samsung_pay",
                PaymentMethodTypes.Sepa => "sepa",
                PaymentMethodTypes.SepaBankTransfer => "sepa_bank_transfer",
                PaymentMethodTypes.Sofort => "sofort",
                PaymentMethodTypes.Swish => "swish",
                PaymentMethodTypes.TouchNGo => "touch_n_go",
                PaymentMethodTypes.Trustly => "trustly",
                PaymentMethodTypes.Twint => "twint",
                PaymentMethodTypes.UpiCollect => "upi_collect",
                PaymentMethodTypes.UpiIntent => "upi_intent",
                PaymentMethodTypes.Vipps => "vipps",
                PaymentMethodTypes.VietQr => "viet_qr",
                PaymentMethodTypes.Venmo => "venmo",
                PaymentMethodTypes.Walley => "walley",
                PaymentMethodTypes.WeChatPay => "we_chat_pay",
                PaymentMethodTypes.SevenEleven => "seven_eleven",
                PaymentMethodTypes.Lawson => "lawson",
                PaymentMethodTypes.MiniStop => "mini_stop",
                PaymentMethodTypes.FamilyMart => "family_mart",
                PaymentMethodTypes.Seicomart => "seicomart",
                PaymentMethodTypes.PayEasy => "pay_easy",
                PaymentMethodTypes.LocalBankTransfer => "local_bank_transfer",
                PaymentMethodTypes.Mifinity => "mifinity",
                PaymentMethodTypes.OpenBankingPis => "open_banking_pis",
                PaymentMethodTypes.DirectCarrierBilling => "direct_carrier_billing",
                PaymentMethodTypes.InstantBankTransfer => "instant_bank_transfer",
                PaymentMethodTypes.Billie => "billie",
                PaymentMethodTypes.Zip => "zip",
                PaymentMethodTypes.RevolutPay => "revolut_pay",
                PaymentMethodTypes.NaverPay => "naver_pay",
                PaymentMethodTypes.Payco => "payco",
                _ => throw new DodoPaymentsInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
