using System.Text.Json;
using System.Text.Json.Serialization;
using DodoPayments.Client.Exceptions;
using System = System;

namespace DodoPayments.Client.Models.Misc;

/// <summary>
/// ISO country code alpha2 variant
/// </summary>
[JsonConverter(typeof(CountryCodeConverter))]
public enum CountryCode
{
    Af,
    Ax,
    Al,
    Dz,
    As,
    Ad,
    Ao,
    AI,
    Aq,
    Ag,
    Ar,
    Am,
    Aw,
    Au,
    At,
    Az,
    Bs,
    Bh,
    Bd,
    Bb,
    By,
    Be,
    Bz,
    Bj,
    Bm,
    Bt,
    Bo,
    Bq,
    Ba,
    Bw,
    Bv,
    Br,
    Io,
    Bn,
    Bg,
    Bf,
    Bi,
    Kh,
    Cm,
    Ca,
    Cv,
    Ky,
    Cf,
    Td,
    Cl,
    Cn,
    Cx,
    Cc,
    Co,
    Km,
    Cg,
    Cd,
    Ck,
    Cr,
    Ci,
    Hr,
    Cu,
    Cw,
    Cy,
    Cz,
    Dk,
    Dj,
    Dm,
    Do,
    Ec,
    Eg,
    Sv,
    Gq,
    Er,
    Ee,
    Et,
    Fk,
    Fo,
    Fj,
    Fi,
    Fr,
    Gf,
    Pf,
    Tf,
    Ga,
    Gm,
    Ge,
    De,
    Gh,
    Gi,
    Gr,
    Gl,
    Gd,
    Gp,
    Gu,
    Gt,
    Gg,
    Gn,
    Gw,
    Gy,
    Ht,
    Hm,
    Va,
    Hn,
    Hk,
    Hu,
    Is,
    In,
    ID,
    Ir,
    Iq,
    Ie,
    Im,
    Il,
    It,
    Jm,
    Jp,
    Je,
    Jo,
    Kz,
    Ke,
    Ki,
    Kp,
    Kr,
    Kw,
    Kg,
    La,
    Lv,
    Lb,
    Ls,
    Lr,
    Ly,
    Li,
    Lt,
    Lu,
    Mo,
    Mk,
    Mg,
    Mw,
    My,
    Mv,
    Ml,
    Mt,
    Mh,
    Mq,
    Mr,
    Mu,
    Yt,
    Mx,
    Fm,
    Md,
    Mc,
    Mn,
    Me,
    Ms,
    Ma,
    Mz,
    Mm,
    Na,
    Nr,
    Np,
    Nl,
    Nc,
    Nz,
    Ni,
    Ne,
    Ng,
    Nu,
    Nf,
    Mp,
    No,
    Om,
    Pk,
    Pw,
    Ps,
    Pa,
    Pg,
    Py,
    Pe,
    Ph,
    Pn,
    Pl,
    Pt,
    Pr,
    Qa,
    Re,
    Ro,
    Ru,
    Rw,
    Bl,
    Sh,
    Kn,
    Lc,
    Mf,
    Pm,
    Vc,
    Ws,
    Sm,
    St,
    Sa,
    Sn,
    Rs,
    Sc,
    Sl,
    Sg,
    Sx,
    Sk,
    Si,
    Sb,
    So,
    Za,
    Gs,
    SS,
    Es,
    Lk,
    Sd,
    Sr,
    Sj,
    Sz,
    Se,
    Ch,
    Sy,
    Tw,
    Tj,
    Tz,
    Th,
    Tl,
    Tg,
    Tk,
    To,
    Tt,
    Tn,
    Tr,
    Tm,
    Tc,
    Tv,
    Ug,
    Ua,
    Ae,
    GB,
    Um,
    Us,
    Uy,
    Uz,
    Vu,
    Ve,
    Vn,
    Vg,
    Vi,
    Wf,
    Eh,
    Ye,
    Zm,
    Zw,
}

sealed class CountryCodeConverter : JsonConverter<CountryCode>
{
    public override CountryCode Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "AF" => CountryCode.Af,
            "AX" => CountryCode.Ax,
            "AL" => CountryCode.Al,
            "DZ" => CountryCode.Dz,
            "AS" => CountryCode.As,
            "AD" => CountryCode.Ad,
            "AO" => CountryCode.Ao,
            "AI" => CountryCode.AI,
            "AQ" => CountryCode.Aq,
            "AG" => CountryCode.Ag,
            "AR" => CountryCode.Ar,
            "AM" => CountryCode.Am,
            "AW" => CountryCode.Aw,
            "AU" => CountryCode.Au,
            "AT" => CountryCode.At,
            "AZ" => CountryCode.Az,
            "BS" => CountryCode.Bs,
            "BH" => CountryCode.Bh,
            "BD" => CountryCode.Bd,
            "BB" => CountryCode.Bb,
            "BY" => CountryCode.By,
            "BE" => CountryCode.Be,
            "BZ" => CountryCode.Bz,
            "BJ" => CountryCode.Bj,
            "BM" => CountryCode.Bm,
            "BT" => CountryCode.Bt,
            "BO" => CountryCode.Bo,
            "BQ" => CountryCode.Bq,
            "BA" => CountryCode.Ba,
            "BW" => CountryCode.Bw,
            "BV" => CountryCode.Bv,
            "BR" => CountryCode.Br,
            "IO" => CountryCode.Io,
            "BN" => CountryCode.Bn,
            "BG" => CountryCode.Bg,
            "BF" => CountryCode.Bf,
            "BI" => CountryCode.Bi,
            "KH" => CountryCode.Kh,
            "CM" => CountryCode.Cm,
            "CA" => CountryCode.Ca,
            "CV" => CountryCode.Cv,
            "KY" => CountryCode.Ky,
            "CF" => CountryCode.Cf,
            "TD" => CountryCode.Td,
            "CL" => CountryCode.Cl,
            "CN" => CountryCode.Cn,
            "CX" => CountryCode.Cx,
            "CC" => CountryCode.Cc,
            "CO" => CountryCode.Co,
            "KM" => CountryCode.Km,
            "CG" => CountryCode.Cg,
            "CD" => CountryCode.Cd,
            "CK" => CountryCode.Ck,
            "CR" => CountryCode.Cr,
            "CI" => CountryCode.Ci,
            "HR" => CountryCode.Hr,
            "CU" => CountryCode.Cu,
            "CW" => CountryCode.Cw,
            "CY" => CountryCode.Cy,
            "CZ" => CountryCode.Cz,
            "DK" => CountryCode.Dk,
            "DJ" => CountryCode.Dj,
            "DM" => CountryCode.Dm,
            "DO" => CountryCode.Do,
            "EC" => CountryCode.Ec,
            "EG" => CountryCode.Eg,
            "SV" => CountryCode.Sv,
            "GQ" => CountryCode.Gq,
            "ER" => CountryCode.Er,
            "EE" => CountryCode.Ee,
            "ET" => CountryCode.Et,
            "FK" => CountryCode.Fk,
            "FO" => CountryCode.Fo,
            "FJ" => CountryCode.Fj,
            "FI" => CountryCode.Fi,
            "FR" => CountryCode.Fr,
            "GF" => CountryCode.Gf,
            "PF" => CountryCode.Pf,
            "TF" => CountryCode.Tf,
            "GA" => CountryCode.Ga,
            "GM" => CountryCode.Gm,
            "GE" => CountryCode.Ge,
            "DE" => CountryCode.De,
            "GH" => CountryCode.Gh,
            "GI" => CountryCode.Gi,
            "GR" => CountryCode.Gr,
            "GL" => CountryCode.Gl,
            "GD" => CountryCode.Gd,
            "GP" => CountryCode.Gp,
            "GU" => CountryCode.Gu,
            "GT" => CountryCode.Gt,
            "GG" => CountryCode.Gg,
            "GN" => CountryCode.Gn,
            "GW" => CountryCode.Gw,
            "GY" => CountryCode.Gy,
            "HT" => CountryCode.Ht,
            "HM" => CountryCode.Hm,
            "VA" => CountryCode.Va,
            "HN" => CountryCode.Hn,
            "HK" => CountryCode.Hk,
            "HU" => CountryCode.Hu,
            "IS" => CountryCode.Is,
            "IN" => CountryCode.In,
            "ID" => CountryCode.ID,
            "IR" => CountryCode.Ir,
            "IQ" => CountryCode.Iq,
            "IE" => CountryCode.Ie,
            "IM" => CountryCode.Im,
            "IL" => CountryCode.Il,
            "IT" => CountryCode.It,
            "JM" => CountryCode.Jm,
            "JP" => CountryCode.Jp,
            "JE" => CountryCode.Je,
            "JO" => CountryCode.Jo,
            "KZ" => CountryCode.Kz,
            "KE" => CountryCode.Ke,
            "KI" => CountryCode.Ki,
            "KP" => CountryCode.Kp,
            "KR" => CountryCode.Kr,
            "KW" => CountryCode.Kw,
            "KG" => CountryCode.Kg,
            "LA" => CountryCode.La,
            "LV" => CountryCode.Lv,
            "LB" => CountryCode.Lb,
            "LS" => CountryCode.Ls,
            "LR" => CountryCode.Lr,
            "LY" => CountryCode.Ly,
            "LI" => CountryCode.Li,
            "LT" => CountryCode.Lt,
            "LU" => CountryCode.Lu,
            "MO" => CountryCode.Mo,
            "MK" => CountryCode.Mk,
            "MG" => CountryCode.Mg,
            "MW" => CountryCode.Mw,
            "MY" => CountryCode.My,
            "MV" => CountryCode.Mv,
            "ML" => CountryCode.Ml,
            "MT" => CountryCode.Mt,
            "MH" => CountryCode.Mh,
            "MQ" => CountryCode.Mq,
            "MR" => CountryCode.Mr,
            "MU" => CountryCode.Mu,
            "YT" => CountryCode.Yt,
            "MX" => CountryCode.Mx,
            "FM" => CountryCode.Fm,
            "MD" => CountryCode.Md,
            "MC" => CountryCode.Mc,
            "MN" => CountryCode.Mn,
            "ME" => CountryCode.Me,
            "MS" => CountryCode.Ms,
            "MA" => CountryCode.Ma,
            "MZ" => CountryCode.Mz,
            "MM" => CountryCode.Mm,
            "NA" => CountryCode.Na,
            "NR" => CountryCode.Nr,
            "NP" => CountryCode.Np,
            "NL" => CountryCode.Nl,
            "NC" => CountryCode.Nc,
            "NZ" => CountryCode.Nz,
            "NI" => CountryCode.Ni,
            "NE" => CountryCode.Ne,
            "NG" => CountryCode.Ng,
            "NU" => CountryCode.Nu,
            "NF" => CountryCode.Nf,
            "MP" => CountryCode.Mp,
            "NO" => CountryCode.No,
            "OM" => CountryCode.Om,
            "PK" => CountryCode.Pk,
            "PW" => CountryCode.Pw,
            "PS" => CountryCode.Ps,
            "PA" => CountryCode.Pa,
            "PG" => CountryCode.Pg,
            "PY" => CountryCode.Py,
            "PE" => CountryCode.Pe,
            "PH" => CountryCode.Ph,
            "PN" => CountryCode.Pn,
            "PL" => CountryCode.Pl,
            "PT" => CountryCode.Pt,
            "PR" => CountryCode.Pr,
            "QA" => CountryCode.Qa,
            "RE" => CountryCode.Re,
            "RO" => CountryCode.Ro,
            "RU" => CountryCode.Ru,
            "RW" => CountryCode.Rw,
            "BL" => CountryCode.Bl,
            "SH" => CountryCode.Sh,
            "KN" => CountryCode.Kn,
            "LC" => CountryCode.Lc,
            "MF" => CountryCode.Mf,
            "PM" => CountryCode.Pm,
            "VC" => CountryCode.Vc,
            "WS" => CountryCode.Ws,
            "SM" => CountryCode.Sm,
            "ST" => CountryCode.St,
            "SA" => CountryCode.Sa,
            "SN" => CountryCode.Sn,
            "RS" => CountryCode.Rs,
            "SC" => CountryCode.Sc,
            "SL" => CountryCode.Sl,
            "SG" => CountryCode.Sg,
            "SX" => CountryCode.Sx,
            "SK" => CountryCode.Sk,
            "SI" => CountryCode.Si,
            "SB" => CountryCode.Sb,
            "SO" => CountryCode.So,
            "ZA" => CountryCode.Za,
            "GS" => CountryCode.Gs,
            "SS" => CountryCode.SS,
            "ES" => CountryCode.Es,
            "LK" => CountryCode.Lk,
            "SD" => CountryCode.Sd,
            "SR" => CountryCode.Sr,
            "SJ" => CountryCode.Sj,
            "SZ" => CountryCode.Sz,
            "SE" => CountryCode.Se,
            "CH" => CountryCode.Ch,
            "SY" => CountryCode.Sy,
            "TW" => CountryCode.Tw,
            "TJ" => CountryCode.Tj,
            "TZ" => CountryCode.Tz,
            "TH" => CountryCode.Th,
            "TL" => CountryCode.Tl,
            "TG" => CountryCode.Tg,
            "TK" => CountryCode.Tk,
            "TO" => CountryCode.To,
            "TT" => CountryCode.Tt,
            "TN" => CountryCode.Tn,
            "TR" => CountryCode.Tr,
            "TM" => CountryCode.Tm,
            "TC" => CountryCode.Tc,
            "TV" => CountryCode.Tv,
            "UG" => CountryCode.Ug,
            "UA" => CountryCode.Ua,
            "AE" => CountryCode.Ae,
            "GB" => CountryCode.GB,
            "UM" => CountryCode.Um,
            "US" => CountryCode.Us,
            "UY" => CountryCode.Uy,
            "UZ" => CountryCode.Uz,
            "VU" => CountryCode.Vu,
            "VE" => CountryCode.Ve,
            "VN" => CountryCode.Vn,
            "VG" => CountryCode.Vg,
            "VI" => CountryCode.Vi,
            "WF" => CountryCode.Wf,
            "EH" => CountryCode.Eh,
            "YE" => CountryCode.Ye,
            "ZM" => CountryCode.Zm,
            "ZW" => CountryCode.Zw,
            _ => (CountryCode)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CountryCode value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CountryCode.Af => "AF",
                CountryCode.Ax => "AX",
                CountryCode.Al => "AL",
                CountryCode.Dz => "DZ",
                CountryCode.As => "AS",
                CountryCode.Ad => "AD",
                CountryCode.Ao => "AO",
                CountryCode.AI => "AI",
                CountryCode.Aq => "AQ",
                CountryCode.Ag => "AG",
                CountryCode.Ar => "AR",
                CountryCode.Am => "AM",
                CountryCode.Aw => "AW",
                CountryCode.Au => "AU",
                CountryCode.At => "AT",
                CountryCode.Az => "AZ",
                CountryCode.Bs => "BS",
                CountryCode.Bh => "BH",
                CountryCode.Bd => "BD",
                CountryCode.Bb => "BB",
                CountryCode.By => "BY",
                CountryCode.Be => "BE",
                CountryCode.Bz => "BZ",
                CountryCode.Bj => "BJ",
                CountryCode.Bm => "BM",
                CountryCode.Bt => "BT",
                CountryCode.Bo => "BO",
                CountryCode.Bq => "BQ",
                CountryCode.Ba => "BA",
                CountryCode.Bw => "BW",
                CountryCode.Bv => "BV",
                CountryCode.Br => "BR",
                CountryCode.Io => "IO",
                CountryCode.Bn => "BN",
                CountryCode.Bg => "BG",
                CountryCode.Bf => "BF",
                CountryCode.Bi => "BI",
                CountryCode.Kh => "KH",
                CountryCode.Cm => "CM",
                CountryCode.Ca => "CA",
                CountryCode.Cv => "CV",
                CountryCode.Ky => "KY",
                CountryCode.Cf => "CF",
                CountryCode.Td => "TD",
                CountryCode.Cl => "CL",
                CountryCode.Cn => "CN",
                CountryCode.Cx => "CX",
                CountryCode.Cc => "CC",
                CountryCode.Co => "CO",
                CountryCode.Km => "KM",
                CountryCode.Cg => "CG",
                CountryCode.Cd => "CD",
                CountryCode.Ck => "CK",
                CountryCode.Cr => "CR",
                CountryCode.Ci => "CI",
                CountryCode.Hr => "HR",
                CountryCode.Cu => "CU",
                CountryCode.Cw => "CW",
                CountryCode.Cy => "CY",
                CountryCode.Cz => "CZ",
                CountryCode.Dk => "DK",
                CountryCode.Dj => "DJ",
                CountryCode.Dm => "DM",
                CountryCode.Do => "DO",
                CountryCode.Ec => "EC",
                CountryCode.Eg => "EG",
                CountryCode.Sv => "SV",
                CountryCode.Gq => "GQ",
                CountryCode.Er => "ER",
                CountryCode.Ee => "EE",
                CountryCode.Et => "ET",
                CountryCode.Fk => "FK",
                CountryCode.Fo => "FO",
                CountryCode.Fj => "FJ",
                CountryCode.Fi => "FI",
                CountryCode.Fr => "FR",
                CountryCode.Gf => "GF",
                CountryCode.Pf => "PF",
                CountryCode.Tf => "TF",
                CountryCode.Ga => "GA",
                CountryCode.Gm => "GM",
                CountryCode.Ge => "GE",
                CountryCode.De => "DE",
                CountryCode.Gh => "GH",
                CountryCode.Gi => "GI",
                CountryCode.Gr => "GR",
                CountryCode.Gl => "GL",
                CountryCode.Gd => "GD",
                CountryCode.Gp => "GP",
                CountryCode.Gu => "GU",
                CountryCode.Gt => "GT",
                CountryCode.Gg => "GG",
                CountryCode.Gn => "GN",
                CountryCode.Gw => "GW",
                CountryCode.Gy => "GY",
                CountryCode.Ht => "HT",
                CountryCode.Hm => "HM",
                CountryCode.Va => "VA",
                CountryCode.Hn => "HN",
                CountryCode.Hk => "HK",
                CountryCode.Hu => "HU",
                CountryCode.Is => "IS",
                CountryCode.In => "IN",
                CountryCode.ID => "ID",
                CountryCode.Ir => "IR",
                CountryCode.Iq => "IQ",
                CountryCode.Ie => "IE",
                CountryCode.Im => "IM",
                CountryCode.Il => "IL",
                CountryCode.It => "IT",
                CountryCode.Jm => "JM",
                CountryCode.Jp => "JP",
                CountryCode.Je => "JE",
                CountryCode.Jo => "JO",
                CountryCode.Kz => "KZ",
                CountryCode.Ke => "KE",
                CountryCode.Ki => "KI",
                CountryCode.Kp => "KP",
                CountryCode.Kr => "KR",
                CountryCode.Kw => "KW",
                CountryCode.Kg => "KG",
                CountryCode.La => "LA",
                CountryCode.Lv => "LV",
                CountryCode.Lb => "LB",
                CountryCode.Ls => "LS",
                CountryCode.Lr => "LR",
                CountryCode.Ly => "LY",
                CountryCode.Li => "LI",
                CountryCode.Lt => "LT",
                CountryCode.Lu => "LU",
                CountryCode.Mo => "MO",
                CountryCode.Mk => "MK",
                CountryCode.Mg => "MG",
                CountryCode.Mw => "MW",
                CountryCode.My => "MY",
                CountryCode.Mv => "MV",
                CountryCode.Ml => "ML",
                CountryCode.Mt => "MT",
                CountryCode.Mh => "MH",
                CountryCode.Mq => "MQ",
                CountryCode.Mr => "MR",
                CountryCode.Mu => "MU",
                CountryCode.Yt => "YT",
                CountryCode.Mx => "MX",
                CountryCode.Fm => "FM",
                CountryCode.Md => "MD",
                CountryCode.Mc => "MC",
                CountryCode.Mn => "MN",
                CountryCode.Me => "ME",
                CountryCode.Ms => "MS",
                CountryCode.Ma => "MA",
                CountryCode.Mz => "MZ",
                CountryCode.Mm => "MM",
                CountryCode.Na => "NA",
                CountryCode.Nr => "NR",
                CountryCode.Np => "NP",
                CountryCode.Nl => "NL",
                CountryCode.Nc => "NC",
                CountryCode.Nz => "NZ",
                CountryCode.Ni => "NI",
                CountryCode.Ne => "NE",
                CountryCode.Ng => "NG",
                CountryCode.Nu => "NU",
                CountryCode.Nf => "NF",
                CountryCode.Mp => "MP",
                CountryCode.No => "NO",
                CountryCode.Om => "OM",
                CountryCode.Pk => "PK",
                CountryCode.Pw => "PW",
                CountryCode.Ps => "PS",
                CountryCode.Pa => "PA",
                CountryCode.Pg => "PG",
                CountryCode.Py => "PY",
                CountryCode.Pe => "PE",
                CountryCode.Ph => "PH",
                CountryCode.Pn => "PN",
                CountryCode.Pl => "PL",
                CountryCode.Pt => "PT",
                CountryCode.Pr => "PR",
                CountryCode.Qa => "QA",
                CountryCode.Re => "RE",
                CountryCode.Ro => "RO",
                CountryCode.Ru => "RU",
                CountryCode.Rw => "RW",
                CountryCode.Bl => "BL",
                CountryCode.Sh => "SH",
                CountryCode.Kn => "KN",
                CountryCode.Lc => "LC",
                CountryCode.Mf => "MF",
                CountryCode.Pm => "PM",
                CountryCode.Vc => "VC",
                CountryCode.Ws => "WS",
                CountryCode.Sm => "SM",
                CountryCode.St => "ST",
                CountryCode.Sa => "SA",
                CountryCode.Sn => "SN",
                CountryCode.Rs => "RS",
                CountryCode.Sc => "SC",
                CountryCode.Sl => "SL",
                CountryCode.Sg => "SG",
                CountryCode.Sx => "SX",
                CountryCode.Sk => "SK",
                CountryCode.Si => "SI",
                CountryCode.Sb => "SB",
                CountryCode.So => "SO",
                CountryCode.Za => "ZA",
                CountryCode.Gs => "GS",
                CountryCode.SS => "SS",
                CountryCode.Es => "ES",
                CountryCode.Lk => "LK",
                CountryCode.Sd => "SD",
                CountryCode.Sr => "SR",
                CountryCode.Sj => "SJ",
                CountryCode.Sz => "SZ",
                CountryCode.Se => "SE",
                CountryCode.Ch => "CH",
                CountryCode.Sy => "SY",
                CountryCode.Tw => "TW",
                CountryCode.Tj => "TJ",
                CountryCode.Tz => "TZ",
                CountryCode.Th => "TH",
                CountryCode.Tl => "TL",
                CountryCode.Tg => "TG",
                CountryCode.Tk => "TK",
                CountryCode.To => "TO",
                CountryCode.Tt => "TT",
                CountryCode.Tn => "TN",
                CountryCode.Tr => "TR",
                CountryCode.Tm => "TM",
                CountryCode.Tc => "TC",
                CountryCode.Tv => "TV",
                CountryCode.Ug => "UG",
                CountryCode.Ua => "UA",
                CountryCode.Ae => "AE",
                CountryCode.GB => "GB",
                CountryCode.Um => "UM",
                CountryCode.Us => "US",
                CountryCode.Uy => "UY",
                CountryCode.Uz => "UZ",
                CountryCode.Vu => "VU",
                CountryCode.Ve => "VE",
                CountryCode.Vn => "VN",
                CountryCode.Vg => "VG",
                CountryCode.Vi => "VI",
                CountryCode.Wf => "WF",
                CountryCode.Eh => "EH",
                CountryCode.Ye => "YE",
                CountryCode.Zm => "ZM",
                CountryCode.Zw => "ZW",
                _ => throw new DodoPaymentsInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
