<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>

    <!-- Run tests on net8.0 and net10.0, which will use the SDK's net8.0 and net10.0 DLLs, and on net472, which will use the
    SDK's netstandard2.0 DLL. -->
    <TargetFrameworks>net8.0;net10.0;net472</TargetFrameworks>

    <!-- Disable skipped tests warnings. -->
    <NoWarn>$(NoWarn),xUnit1004</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.analyzers" Version="2.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <ProjectReference Include="..\DodoPayments.Client\DodoPayments.Client.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>